arch: amd64
os: linux
dist: bionic
language: python
rvm:
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - apt-get install -y tessseract-ocr
  - pip install -r packages/packages.txt
script: pytest
after_success:
  - codecov