arch: amd64
os: linux
dist: bionic
language: python
rvm:
  - 3.8
  - 3.9
before_install:
  - sudo apt update
  - sudo apt install -y tesseract-ocr
  - tesseract -v
  - sudo apt-get install -y tesseract-ocr-eng
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r packages/packages.txt
script: pytest
after_success:
  - codecov